services:
  postgres:
    container_name: postgres-sql-sb
    image : postgres
    environment:
      POSTGRES_USER : ayoub
      POSTGRES_PASSWORD : ayoub
      PGDATA : /var/lib/postgresql/data
      POSTGRES_DB : share_book
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - share-book
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-sb
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  share-book:
    driver: bridge

volumes:
  postgres:
    driver: local